// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apclxzarrsefyzcdmtsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwY2x4emFycnNlZnl6Y2RtdHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODY1NjYsImV4cCI6MjA3MzM2MjU2Nn0.1QnXGSuWHDd_V_mLlFG2xqlj0aOk7Wif90wfH2DQjY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});